spring.datasource.url=${EINV_DB_URL}
spring.datasource.username=${EINV_DB_USERNAME}
spring.datasource.password=${EINV_DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

server.error.include-message=never
server.error.include-stacktrace=never

hacienda.auth.url=${HACIENDA_AUTH_URL}
hacienda.api.url=${HACIENDA_API_URL}
hacienda.client.id=${HACIENDA_CLIENT_ID}
hacienda.username=${HACIENDA_USERNAME}
hacienda.password=${HACIENDA_PASSWORD}

security.jwt.secret=${JWT_SECRET}
security.jwt.expiration-seconds=3600

